// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title ICastleLease
/// @notice The giant's castle lease: the one piece of state every fee-fi-fo-fum component agrees on.
/// @dev Castle.sol implements it. FeeFiFoFumExtruction fences fills on it, fo signs the attestations it
///      checks, and fee/fi/fum drive it. The lease is the ENSv2 name castle.feefifofum.eth:
///      - `holder`  the shift currently allowed to ship, dock and renew (the giant awake at the desk);
///      - `epoch`   the fencing epoch, the name's registry token id, regenerated by every claim. A program
///                  shipped under an older epoch is a stale shift, and its fills revert FeeFiFoFum();
///      - `expiry`  unix seconds; after it the shift is only EXPIRED (fills wind down) until someone claims.
///      If the ENSv2 probes show the token id is not regenerated on re-registration, `epoch` is Castle's own
///      counter, bumped on every claim, and `expiry` is still read from the registry.
interface ICastleLease {
    /// @notice What fo signs (EIP-712) to let the holder extend the lease to `expiry`.
    /// @dev Domain: name "fee-fi-fo-fum Castle", version "1", chainId, verifyingContract = Castle.
    ///      Type:   Attestation(uint256 epoch,uint64 expiry,uint64 deadline)
    ///      `epoch` must equal the live epoch, so an attestation cannot outlive the shift it was signed for;
    ///      `expiry` must be later than the current expiry, so a used attestation cannot be replayed;
    ///      `deadline` bounds how long an unused attestation stays valid.
    struct Attestation {
        uint256 epoch;
        uint64 expiry;
        uint64 deadline;
    }

    /// @notice The lease was extended by its holder with fo's attestation.
    event LeaseRenewed(address indexed holder, uint256 indexed epoch, uint64 expiry);
    /// @notice The lease changed hands after expiry; `epoch` is the new fencing epoch.
    event LeaseClaimed(address indexed holder, uint256 indexed epoch, uint256 previousEpoch, uint64 expiry);

    /// @notice Caller is not the lease holder.
    error NotHolder(address caller, address holder);
    /// @notice The lease has expired; the holder must be replaced through claim().
    error LeaseExpired(uint64 expiry);
    /// @notice The lease is still live, so it cannot be claimed.
    error LeaseStillLive(uint64 expiry);
    /// @notice The attestation was not signed by fo.
    error BadAttestation(address signer);
    /// @notice The attestation is for another epoch.
    error StaleAttestation(uint256 attestedEpoch, uint256 epoch);
    /// @notice The attestation's deadline has passed.
    error AttestationExpired(uint64 deadline);
    /// @notice The requested expiry does not extend the lease (this is what a replayed attestation hits),
    ///         or reaches past now + leasePeriod().
    error BadExpiry(uint64 requested, uint64 current, uint64 max);

    /// @notice The current lease holder.
    function holder() external view returns (address);

    /// @notice The current fencing epoch.
    function epoch() external view returns (uint256);

    /// @notice The lease expiry, in unix seconds.
    function expiry() external view returns (uint64);

    /// @notice True while block.timestamp < expiry().
    function isLive() external view returns (bool);

    /// @notice The fencer whose attestation every renew needs.
    function fo() external view returns (address);

    /// @notice The longest extension one renew may grant, in seconds (120 in the demo).
    function leasePeriod() external view returns (uint64);

    /// @notice The EIP-712 digest fo signs for `att`, computed under this castle's domain.
    function attestationDigest(Attestation calldata att) external view returns (bytes32);

    /// @notice Extend the lease to `newExpiry`. Holder only, and only with fo's signature over
    ///         Attestation(epoch(), newExpiry, deadline).
    function renew(uint64 newExpiry, uint64 deadline, bytes calldata foSig) external;

    /// @notice After expiry, take the castle: re-register the name to the caller, which starts a new epoch.
    function claim() external returns (uint256 newEpoch);
}

/// @notice The EIP-712 constants fo and Castle must agree on.
library CastleLeaseTypes {
    string internal constant NAME = "fee-fi-fo-fum Castle";
    string internal constant VERSION = "1";
    bytes32 internal constant ATTESTATION_TYPEHASH = keccak256("Attestation(uint256 epoch,uint64 expiry,uint64 deadline)");
}
